In [2]:
import pandas as pd

In [3]:
df = pd.read_excel(r"C:\Users\SVKUSER\Downloads\Attribute DataSet (1).xlsx")

In [4]:
df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [7]:
type(df)

pandas.core.frame.DataFrame

In [8]:
df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [9]:
pd.read_excel(r'C:\Users\SVKUSER\Downloads\Attribute DataSet (1).xlsx', sheet_name="Sheet2")

,Average,4.5,M,Spring,v-neck,short,empire,cotton,null,button
0,Average,5.0,free,Spring,v-neck,sleevless,natural,cotton,broadcloth,lace
1,Low,4.4,L,Automn,o-neck,halfsleeve,natural,rayon,chiffon,sashes
2,Average,4.8,M,Winter,o-neck,short,natural,lycra,broadcloth,applique
3,Low,4.8,free,Spring,o-neck,sleevless,natural,cotton,NaN,NaN
4,Average,4.8,M,Winter,o-neck,sleevless,natural,cotton,NaN,NaN
5,Average,0.0,M,Winter,o-neck,short,natural,NaN,NaN,lace
6,Average,4.8,L,Spring,v-neck,threequarter,empire,polyster,NaN,lace
7,Average,0.0,M,Summer,o-neck,halfsleeve,natural,cotton,chiffon,ruffles
8,Low,4.7,M,Summer,o-neck,sleevless,empire,milksilk,NaN,NaN
9,Medium,0.0,L,Winter,boat-neck,full,empire,NaN,NaN,NaN
10,Low,5.0,free,Summer,v-neck,sleevless,empire,NaN,chiffon,NaN
11,Low,4.3,free,Summer,o-neck,sleevless,NaN,milksilk,NaN,NaN
12,Average,0.0,L,Spring,o-neck,halfsleeve,natural,polyster,chiffon,hollowout

In [10]:
pd.read_excel(r'C:\Users\SVKUSER\Downloads\Attribute DataSet (1).xlsx', sheet_name="Sheet3", header = None)

            0          1          2          3
0         NaN        NaN        NaN        NaN
1     Average     v-neck        NaN        NaN
2         Low     o-neck        NaN     v-neck
3     Average     o-neck        NaN     o-neck
4         Low  boat-neck        NaN     o-neck
5         NaN        NaN        NaN  boat-neck
6         NaN        NaN     v-neck        NaN
7      v-neck        NaN     o-neck        NaN
8      o-neck        NaN     o-neck        NaN
9      o-neck        NaN  boat-neck        NaN
10  boat-neck        NaN        NaN        NaN
11        NaN     v-neck        NaN        NaN
12        NaN     o-neck        NaN        NaN
13        NaN     o-neck        NaN        NaN
14        NaN  boat-neck        NaN        NaN

In [11]:
pd.read_excel(r'C:\Users\SVKUSER\Downloads\Attribute DataSet (1).xlsx', sheet_name="Sheet3", header = None)

            0          1          2          3
0         NaN        NaN        NaN        NaN
1     Average     v-neck        NaN        NaN
2         Low     o-neck        NaN     v-neck
3     Average     o-neck        NaN     o-neck
4         Low  boat-neck        NaN     o-neck
5         NaN        NaN        NaN  boat-neck
6         NaN        NaN     v-neck        NaN
7      v-neck        NaN     o-neck        NaN
8      o-neck        NaN     o-neck        NaN
9      o-neck        NaN  boat-neck        NaN
10  boat-neck        NaN        NaN        NaN
11        NaN     v-neck        NaN        NaN
12        NaN     o-neck        NaN        NaN
13        NaN     o-neck        NaN        NaN
14        NaN  boat-neck        NaN        NaN

In [12]:
pd.read_excel(r'C:\Users\SVKUSER\Downloads\Attribute DataSet (1).xlsx', sheet_name="Sheet3", header = None, names =['A','B','C'])

                   A          B          C
NaN              NaN        NaN        NaN
Average       v-neck        NaN        NaN
Low           o-neck        NaN     v-neck
Average       o-neck        NaN     o-neck
Low        boat-neck        NaN     o-neck
NaN              NaN        NaN  boat-neck
NaN              NaN     v-neck        NaN
v-neck           NaN     o-neck        NaN
o-neck           NaN     o-neck        NaN
o-neck           NaN  boat-neck        NaN
boat-neck        NaN        NaN        NaN
NaN           v-neck        NaN        NaN
NaN           o-neck        NaN        NaN
NaN           o-neck        NaN        NaN
NaN        boat-neck        NaN        NaN

In [13]:
pd.read_excel(r"C:\Users\SVKUSER\Downloads\Attribute DataSet (1).xlsx")

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [14]:
df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [15]:
df.head(2)

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0

In [16]:
df.head()

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0

In [17]:
df.tail()

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [18]:
df.tail(2)

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [30]:
pd.read_csv(r'C:\Users\SVKUSER\Downloads\haberman (2).csv', header = None, names =['Age', 'years',])

           Age  years
0    30@64@1@1    NaN
1    30@62@3@1    NaN
2    30@65@0@1    NaN
3    31@59@2@1    NaN
4    31@65@4@1    NaN
..         ...    ...
301  75@62@1@1    NaN
302  76@67@0@1    NaN
303  77@65@3@1    NaN
304  78@65@1@2    NaN
305  83@58@2@2    NaN

[306 rows x 2 columns]

In [31]:
import pandas as pd

In [32]:
pd.read_excel(r"C:\Users\SVKUSER\Downloads\Attribute DataSet (1).xlsx")

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [33]:
pd.read_csv(r"C:\Users\SVKUSER\Downloads\haberman (2).csv", header = None, names =["A","B","c"])

             A   B   c
0    30@64@1@1 NaN NaN
1    30@62@3@1 NaN NaN
2    30@65@0@1 NaN NaN
3    31@59@2@1 NaN NaN
4    31@65@4@1 NaN NaN
..         ...  ..  ..
301  75@62@1@1 NaN NaN
302  76@67@0@1 NaN NaN
303  77@65@3@1 NaN NaN
304  78@65@1@2 NaN NaN
305  83@58@2@2 NaN NaN

[306 rows x 3 columns]

In [34]:
pd.read_csv(r'C:\Users\SVKUSER\Downloads\haberman (2).csv', header = None, names =['Age', "patients's years"])

           Age  patients's years
0    30@64@1@1               NaN
1    30@62@3@1               NaN
2    30@65@0@1               NaN
3    31@59@2@1               NaN
4    31@65@4@1               NaN
..         ...               ...
301  75@62@1@1               NaN
302  76@67@0@1               NaN
303  77@65@3@1               NaN
304  78@65@1@2               NaN
305  83@58@2@2               NaN

[306 rows x 2 columns]

In [35]:
pd.read_csv(r'C:\Users\SVKUSER\Downloads\haberman (2).csv', header = None, names =['Age', "patients's years","number of position", "Survival status"])

           Age  patients's years  number of position  Survival status
0    30@64@1@1               NaN                 NaN              NaN
1    30@62@3@1               NaN                 NaN              NaN
2    30@65@0@1               NaN                 NaN              NaN
3    31@59@2@1               NaN                 NaN              NaN
4    31@65@4@1               NaN                 NaN              NaN
..         ...               ...                 ...              ...
301  75@62@1@1               NaN                 NaN              NaN
302  76@67@0@1               NaN                 NaN              NaN
303  77@65@3@1               NaN                 NaN              NaN
304  78@65@1@2               NaN                 NaN              NaN
305  83@58@2@2               NaN                 NaN              NaN

[306 rows x 4 columns]

In [22]:
pd.read_csv(r"C:\Users\SVKUSER\Downloads\haberman (2).csv")

      30@64@1@1
0     30@62@3@1
1     30@65@0@1
2     31@59@2@1
3     31@65@4@1
4    33@58@10@1
..          ...
300   75@62@1@1
301   76@67@0@1
302   77@65@3@1
303   78@65@1@2
304   83@58@2@2

[305 rows x 1 columns]

In [23]:
pd.read_csv(r"C:\Users\SVKUSER\Downloads\haberman (2).csv", sep = "@")

     30  64   1  1.1
0    30  62   3    1
1    30  65   0    1
2    31  59   2    1
3    31  65   4    1
4    33  58  10    1
..   ..  ..  ..  ...
300  75  62   1    1
301  76  67   0    1
302  77  65   3    1
303  78  65   1    2
304  83  58   2    2

[305 rows x 4 columns]

In [24]:
pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/Smarket.csv")

      Year   Lag1   Lag2   Lag3   Lag4   Lag5   Volume  Today Direction
0     2001  0.381 -0.192 -2.624 -1.055  5.010  1.19130  0.959        Up
1     2001  0.959  0.381 -0.192 -2.624 -1.055  1.29650  1.032        Up
2     2001  1.032  0.959  0.381 -0.192 -2.624  1.41120 -0.623      Down
3     2001 -0.623  1.032  0.959  0.381 -0.192  1.27600  0.614        Up
4     2001  0.614 -0.623  1.032  0.959  0.381  1.20570  0.213        Up
...    ...    ...    ...    ...    ...    ...      ...    ...       ...
1245  2005  0.422  0.252 -0.024 -0.584 -0.285  1.88850  0.043        Up
1246  2005  0.043  0.422  0.252 -0.024 -0.584  1.28581 -0.955      Down
1247  2005 -0.955  0.043  0.422  0.252 -0.024  1.54047  0.130        Up
1248  2005  0.130 -0.955  0.043  0.422  0.252  1.42236 -0.298      Down
1249  2005 -0.298  0.130 -0.955  0.043  0.422  1.38254 -0.489      Down

[1250 rows x 9 columns]

In [44]:
pd.read_html("https://www.basketball-reference.com/leagues/NBA_2015_totals.html")

[      Rk          Player Pos Age   Tm   G  GS    MP   FG  FGA  ...   FT%  ORB  \
 0      1      Quincy Acy  PF  24  NYK  68  22  1287  152  331  ...  .784   79
 1      2    Jordan Adams  SG  20  MEM  30   0   248   35   86  ...  .609    9
 2      3    Steven Adams   C  21  OKC  70  67  1771  217  399  ...  .502  199
 3      4     Jeff Adrien  PF  28  MIN  17   0   215   19   44  ...  .579   23
 4      5   Arron Afflalo  SG  29  TOT  78  72  2502  375  884  ...  .843   27
 ..   ...             ...  ..  ..  ...  ..  ..   ...  ...  ...  ...   ...  ...
 670  490  Thaddeus Young  PF  26  TOT  76  68  2434  451  968  ...  .655  127
 671  490  Thaddeus Young  PF  26  MIN  48  48  1605  289  641  ...  .682   75
 672  490  Thaddeus Young  PF  26  BRK  28  20   829  162  327  ...  .606   52
 673  491     Cody Zeller   C  22  CHO  62  45  1487  172  373  ...  .774   97
 674  492    Tyler Zeller   C  25  BOS  82  59  1731  340  619  ...  .823  146

      DRB  TRB  AST  STL BLK  TOV   PF   PTS
 0    222  301   68   27  22   60  147   398
 1     19   28   16   16   7   14   24    94
 2    324  523   66   38  86   99  222   537
 3     54   77   15    4   9    9   30    60
 4    220  247  129   41   7  116  167  1035
 ..   ...  ...  ...  ...  ..  ...  ...   ...
 670  284  411  173  124  25  117  171  1071
 671  170  245  135   86  17   75  115   685
 672  114  166   38   38   8   42   56   386
 673  265  362  100   34  49   62  156   472
 674  319  465  113   18  52   76  205   833

 [675 rows x 30 columns]]

In [40]:
a = pd.read_html("https://www.basketball-reference.com/leagues/NBA_2015_totals.html")

In [41]:
type(a)

list

In [45]:
a[0]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,968,...,.655,127,284,411,173,124,25,117,171,1071
671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,641,...,.682,75,170,245,135,86,17,75,115,685
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [47]:
len(a)

1

In [48]:
a[0]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,968,...,.655,127,284,411,173,124,25,117,171,1071
671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,641,...,.682,75,170,245,135,86,17,75,115,685
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [51]:
pd.read_json("https://api.github.com/repos/pandas-dev/pandas/issues")

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,closed_at,author_association,active_lock_reason,body,reactions,timeline_url,performed_via_github_app,state_reason,draft,pull_request
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48512,1369283979,I_kwDOAA0YD85RnZ2L,48512,"ENH: Add a ""level="" kwarg to .rename_axis(), f...",...,NaT,NONE,NaN,### Feature Type\r\n\r\n- [X] Adding new funct...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48511,1369256734,PR_kwDOAA0YD84-v-aa,48511,BUG: Fix bug in pd.eval when UnaryOp in function,...,NaT,CONTRIBUTOR,NaN,- [x] closes #46471\r\n- [x] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48510,1369235435,I_kwDOAA0YD85RnN_r,48510,BUG: Appending to empty ExtensionArray removes...,...,NaT,CONTRIBUTOR,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48509,1369230381,I_kwDOAA0YD85RnMwt,48509,BUG: groupby() attempts to converts name of Se...,...,NaT,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48508,1369093149,PR_kwDOAA0YD84-vbcK,48508,TYP: type all arguments with str default values,...,NaT,CONTRIBUTOR,NaN,After this PR autotyping will gently nudge peo...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48507,1369062909,I_kwDOAA0YD85Rmj39,48507,BUG: read_csv with pyarrow engine fails with s...,...,NaT,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48506,1368949190,I_kwDOAA0YD85RmIHG,48506,BUG: groupby doesn't identify null values when...,...,NaT,MEMBER,NaN,Closely related to #48476\r\n\r\nAs far as I c...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48505,1368940526,PR_kwDOAA0YD84-u-Ai,48505,ENH: Keep dtypes in MultiIndex.union without NAs,...,NaT,MEMBER,NaN,- [ ] closes #xxxx (Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48504,1368810165,PR_kwDOAA0YD84-uk8D,48504,PERF: merge on sorted MultiIndex,...,NaT,MEMBER,NaN,- [x] [Tests added and passed](https://pandas....,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48503,1368799601,I_kwDOAA0YD85Rljlx,48503,ENH: `.merge` - specify string literals for `....,...,NaT,NONE,NaN,### Feature Type\n\n- [ ] Adding new functiona...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48502,1368752314,PR_kwDOAA0YD84-uY5E,48502,SAS7BDAT parser: Speed up blank_missing,...,NaT,CONTRIBUTOR,NaN,Move `blank_missing` to Cython.\r\n\r\nASV:\r\...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48500,1368693607,PR_kwDOAA0YD84-uN1n,48500,DOC: Add SeriesGroupBy and DataFrameGroupBy re...,...,NaT,MEMBER,NaN,- [x] closes #48399 (Replace xxxx with the Gi...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48499,1368629601,I_kwDOAA0YD85Rk6Fh,48499,pd.concat high memory consumption after read_csv,...,NaT,NONE,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48498,1368614569,PR_kwDOAA0YD84-t-5_,48498,BUG: MultiIndex.union losing extension array d...,...,NaT,MEMBER,NaN,- [ ] closes #xxxx (Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48497,1368607135,PR_kwDOAA0YD84-t9hC,48497,Bug: raise TypeError when doing infer_freq usi...,...,NaT,CONTRIBUTOR,NaN,- [x] closes #48439 \r\n- [x] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48496,1368587692,PR_kwDOAA0YD84-t53l,48496,ENH: Support mask properly in GroupBy.quantile,...,NaT,MEMBER,NaN,- [x] xref #37493 (Replace xxxx with the Githu...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48495,1368577188,PR_kwDOAA0YD84-t4AC,48495,BUG/PERF: use lexsort_indexer in MultiIndex.ar...,...,NaT,MEMBER,NaN,- [x] [Tests added and passed](https://pandas....,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48494,1368554146,PR_kwDOAA0YD84-tz4y,48494,Backport PR #48443 on branch 1.5.x (BUG: Fix p...,...,NaT,MEMBER,NaN,#48443\r\n,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48492,1368525342,I_kwDOAA0YD85Rkgoe,48492,BUG: Groupby drops NA even though dropna=False...,...,NaT,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48491,1368450955,PR_kwDOAA0YD84-tf63,48491,WEB: Update Python for Data Analysis book,...,NaT,MEMBER,NaN,None,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48490,1368430593,PR_kwDOAA0YD84-tblF,48490,CI: Use -j1 for python-dev build to avoid flak...,...,NaT,MEMBER,NaN,xref #47305\r\n\r\ne.g. https://github.com/pan...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48489,1368418413,PR_kwDOAA0YD84-tZF_,48489,BUG: fix test_arrow.py tests,...,NaT,MEMBER,NaN,Sits on top of #48428,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48488,1368255987,I_kwDOAA0YD85Rje3z,48488,ENH: df.compare should have tolerances,...,NaT,CONTRIBUTOR,NaN,### Feature Type\n\n- [ ] Adding new functiona...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48487,1368189400,I_kwDOAA0YD85RjOnY,48487,DOC: pandas.read_csv,...,NaT,NONE,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48484,1367833986,PR_kwDOAA0YD84-reKm,48484,BUG: fix valueError for groupby with empty inp...,...,NaT,CONTRIBUTOR,NaN,- [x] closes ##48459\r\n- [x] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48483,1367782315,I_kwDOAA0YD85RhrOr,48483,BUG: [unit test] pandas/io/clipboard/__init__....,...,NaT,NONE,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48482,1367728492,I_kwDOAA0YD85RheFs,48482,BUG: replace with immutable data raising KeyEr...,...,NaT,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48481,1367686165,I_kwDOAA0YD85RhTwV,48481,"ENH: Support ""std"" aggregation in groupby for ...",...,NaT,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48480,1367623880,I_kwDOAA0YD85RhEjI,48480,"BUG: df.fillna(dict, inplace=True) triggers Fu...",...,NaT,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48479,1367498537,I_kwDOAA0YD85Rgl8p,48479,ENH: initialize row DataFrame with list,...,NaT,NONE,NaN,### Feature Type\n\n- [ ] Adding new functiona...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN

In [55]:
js = pd.read_json("https://api.github.com/repos/pandas-dev/pandas/issues")

In [56]:
js

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,closed_at,author_association,active_lock_reason,body,reactions,timeline_url,performed_via_github_app,state_reason,draft,pull_request
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48512,1369283979,I_kwDOAA0YD85RnZ2L,48512,"ENH: Add a ""level="" kwarg to .rename_axis(), f...",...,NaT,NONE,NaN,### Feature Type\r\n\r\n- [X] Adding new funct...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48511,1369256734,PR_kwDOAA0YD84-v-aa,48511,BUG: Fix bug in pd.eval when UnaryOp in function,...,NaT,CONTRIBUTOR,NaN,- [x] closes #46471\r\n- [x] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48510,1369235435,I_kwDOAA0YD85RnN_r,48510,BUG: Appending to empty ExtensionArray removes...,...,NaT,CONTRIBUTOR,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48509,1369230381,I_kwDOAA0YD85RnMwt,48509,BUG: groupby() attempts to converts name of Se...,...,NaT,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48508,1369093149,PR_kwDOAA0YD84-vbcK,48508,TYP: type all arguments with str default values,...,NaT,CONTRIBUTOR,NaN,After this PR autotyping will gently nudge peo...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48507,1369062909,I_kwDOAA0YD85Rmj39,48507,BUG: read_csv with pyarrow engine fails with s...,...,NaT,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48506,1368949190,I_kwDOAA0YD85RmIHG,48506,BUG: groupby doesn't identify null values when...,...,NaT,MEMBER,NaN,Closely related to #48476\r\n\r\nAs far as I c...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48505,1368940526,PR_kwDOAA0YD84-u-Ai,48505,ENH: Keep dtypes in MultiIndex.union without NAs,...,NaT,MEMBER,NaN,- [ ] closes #xxxx (Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48504,1368810165,PR_kwDOAA0YD84-uk8D,48504,PERF: merge on sorted MultiIndex,...,NaT,MEMBER,NaN,- [x] [Tests added and passed](https://pandas....,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48503,1368799601,I_kwDOAA0YD85Rljlx,48503,ENH: `.merge` - specify string literals for `....,...,NaT,NONE,NaN,### Feature Type\n\n- [ ] Adding new functiona...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48502,1368752314,PR_kwDOAA0YD84-uY5E,48502,SAS7BDAT parser: Speed up blank_missing,...,NaT,CONTRIBUTOR,NaN,Move `blank_missing` to Cython.\r\n\r\nASV:\r\...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48500,1368693607,PR_kwDOAA0YD84-uN1n,48500,DOC: Add SeriesGroupBy and DataFrameGroupBy re...,...,NaT,MEMBER,NaN,- [x] closes #48399 (Replace xxxx with the Gi...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48499,1368629601,I_kwDOAA0YD85Rk6Fh,48499,pd.concat high memory consumption after read_csv,...,NaT,NONE,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48498,1368614569,PR_kwDOAA0YD84-t-5_,48498,BUG: MultiIndex.union losing extension array d...,...,NaT,MEMBER,NaN,- [ ] closes #xxxx (Replace xxxx with the Gith...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48497,1368607135,PR_kwDOAA0YD84-t9hC,48497,Bug: raise TypeError when doing infer_freq usi...,...,NaT,CONTRIBUTOR,NaN,- [x] closes #48439 \r\n- [x] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48496,1368587692,PR_kwDOAA0YD84-t53l,48496,ENH: Support mask properly in GroupBy.quantile,...,NaT,MEMBER,NaN,- [x] xref #37493 (Replace xxxx with the Githu...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48495,1368577188,PR_kwDOAA0YD84-t4AC,48495,BUG/PERF: use lexsort_indexer in MultiIndex.ar...,...,NaT,MEMBER,NaN,- [x] [Tests added and passed](https://pandas....,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48494,1368554146,PR_kwDOAA0YD84-tz4y,48494,Backport PR #48443 on branch 1.5.x (BUG: Fix p...,...,NaT,MEMBER,NaN,#48443\r\n,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48492,1368525342,I_kwDOAA0YD85Rkgoe,48492,BUG: Groupby drops NA even though dropna=False...,...,NaT,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48491,1368450955,PR_kwDOAA0YD84-tf63,48491,WEB: Update Python for Data Analysis book,...,NaT,MEMBER,NaN,None,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48490,1368430593,PR_kwDOAA0YD84-tblF,48490,CI: Use -j1 for python-dev build to avoid flak...,...,NaT,MEMBER,NaN,xref #47305\r\n\r\ne.g. https://github.com/pan...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48489,1368418413,PR_kwDOAA0YD84-tZF_,48489,BUG: fix test_arrow.py tests,...,NaT,MEMBER,NaN,Sits on top of #48428,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48488,1368255987,I_kwDOAA0YD85Rje3z,48488,ENH: df.compare should have tolerances,...,NaT,CONTRIBUTOR,NaN,### Feature Type\n\n- [ ] Adding new functiona...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48487,1368189400,I_kwDOAA0YD85RjOnY,48487,DOC: pandas.read_csv,...,NaT,NONE,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/48484,1367833986,PR_kwDOAA0YD84-reKm,48484,BUG: fix valueError for groupby with empty inp...,...,NaT,CONTRIBUTOR,NaN,- [x] closes ##48459\r\n- [x] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48483,1367782315,I_kwDOAA0YD85RhrOr,48483,BUG: [unit test] pandas/io/clipboard/__init__....,...,NaT,NONE,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48482,1367728492,I_kwDOAA0YD85RheFs,48482,BUG: replace with immutable data raising KeyEr...,...,NaT,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48481,1367686165,I_kwDOAA0YD85RhTwV,48481,"ENH: Support ""std"" aggregation in groupby for ...",...,NaT,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48480,1367623880,I_kwDOAA0YD85RhEjI,48480,"BUG: df.fillna(dict, inplace=True) triggers Fu...",...,NaT,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/48479,1367498537,I_kwDOAA0YD85Rgl8p,48479,ENH: initialize row DataFrame with list,...,NaT,NONE,NaN,### Feature Type\n\n- [ ] Adding new functiona...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN

In [59]:
js.columns

Index(['url', 'repository_url', 'labels_url', 'comments_url', 'events_url',
       'html_url', 'id', 'node_id', 'number', 'title', 'user', 'labels',
       'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments',
       'created_at', 'updated_at', 'closed_at', 'author_association',
       'active_lock_reason', 'body', 'reactions', 'timeline_url',
       'performed_via_github_app', 'state_reason', 'draft', 'pull_request'],
      dtype='object')

In [61]:
js['user']

0     {'login': 'gwerbin', 'id': 5758789, 'node_id':...
1     {'login': 'yuanx749', 'id': 47032563, 'node_id...
2     {'login': 'ssche', 'id': 7367411, 'node_id': '...
3     {'login': 'maartenb', 'id': 808867, 'node_id':...
4     {'login': 'twoertwein', 'id': 6618166, 'node_i...
5     {'login': 'dxdc', 'id': 7200365, 'node_id': 'M...
6     {'login': 'rhshadrach', 'id': 45562402, 'node_...
7     {'login': 'phofl', 'id': 61934744, 'node_id': ...
8     {'login': 'lukemanley', 'id': 8519523, 'node_i...
9     {'login': 'alexc-yellowcanary', 'id': 11079634...
10    {'login': 'jonashaag', 'id': 175722, 'node_id'...
11    {'login': 'rhshadrach', 'id': 45562402, 'node_...
12    {'login': 'un000', 'id': 19488486, 'node_id': ...
13    {'login': 'phofl', 'id': 61934744, 'node_id': ...
14    {'login': 'ambujpawar', 'id': 19887541, 'node_...
15    {'login': 'phofl', 'id': 61934744, 'node_id': ...
16    {'login': 'lukemanley', 'id': 8519523, 'node_i...
17    {'login': 'phofl', 'id': 61934744, 'node_id': ...
18    {'login': 'goodyguts', 'id': 22603543, 'node_i...
19    {'login': 'mroeschke', 'id': 10647082, 'node_i...
20    {'login': 'mroeschke', 'id': 10647082, 'node_i...
21    {'login': 'jbrockmendel', 'id': 8078968, 'node...
22    {'login': 'tehunter', 'id': 7980666, 'node_id'...
23    {'login': 'ryanbaekr', 'id': 76887060, 'node_i...
24    {'login': 'Th3nn3ss', 'id': 25160953, 'node_id...
25    {'login': 'adrienpacifico', 'id': 6614121, 'no...
26    {'login': 'fyrestone', 'id': 6308809, 'node_id...
27    {'login': 'PrimozGodec', 'id': 6421558, 'node_...
28    {'login': 'marekro', 'id': 43476190, 'node_id'...
29    {'login': 'mattiatantardini', 'id': 66005981, ...
Name: user, dtype: object

In [62]:
js['user'][0]

{'login': 'gwerbin',
 'id': 5758789,
 'node_id': 'MDQ6VXNlcjU3NTg3ODk=',
 'avatar_url': 'https://avatars.githubusercontent.com/u/5758789?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/gwerbin',
 'html_url': 'https://github.com/gwerbin',
 'followers_url': 'https://api.github.com/users/gwerbin/followers',
 'following_url': 'https://api.github.com/users/gwerbin/following{/other_user}',
 'gists_url': 'https://api.github.com/users/gwerbin/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/gwerbin/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/gwerbin/subscriptions',
 'organizations_url': 'https://api.github.com/users/gwerbin/orgs',
 'repos_url': 'https://api.github.com/users/gwerbin/repos',
 'events_url': 'https://api.github.com/users/gwerbin/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/gwerbin/received_events',
 'type': 'User',
 'site_admin': False}

In [65]:
df= pd.read_excel(r"C:\Users\SVKUSER\Downloads\Attribute DataSet (1).xlsx")

In [66]:
df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [69]:
df.to_json("babblu.json")

In [72]:
pwd

'C:\\Users\\SVKUSER'

In [74]:
df.to_csv("E://babblu.csv")

In [75]:
pwd

'C:\\Users\\SVKUSER'

In [79]:
df.to_csv("E://babblu.csv",sep = "#")

In [80]:
df.to_csv("E://babblu123.csv",sep = "#", index = False)